### PR TITLE
Switch to Bootstrap 4.5.2 and sync repo with CNCF template project

### PR DESCRIPTION
**Pull request by hackabletype**
As per issue https://github.com/dexidp/website/issues/3, PR https://github.com/cncf/hugo-netlify-starter/pull/9 (it was originally PR https://github.com/cncf/hugo-netlify-starter/pull/7) has been merged into cncf/hugo-netlify-starter's main branch. 

This PR brings those upstream changes into the dexidp/website.

### CODE REVIEW

**Comment by celestehorgan** [comment]
@justaugustus It might be prudent to give me merge access to this repository so I can keep this project moving along without you having to approve everything? :)

**Comment by sagikazarmark** [comment]
@celestehorgan I've sent you an invitation with Write access (don't know how these new GH permissions work, so let me know if you need Maintainer access)

**Comment by justaugustus** [comment]
> @justaugustus It might be prudent to give me merge access to this repository so I can keep this project moving along without you having to approve everything? :)

@celestehorgan -- I actually thought I had already done that :sweat_smile: 

> @celestehorgan I've sent you an invitation with Write access (don't know how these new GH permissions work, so let me know if you need Maintainer access)

@sagikazarmark -- I'll check the permissions out later today. We'll want a team for this, as opposed to individual access grants.

**Review by justaugustus — CHANGES_REQUESTED** [review]
Let's not merge this as-is. We want the content changes, but not the git history that has been pulled in.
I'll come back with some git suggestions after my next meeting.

**Comment by hackabletype** [comment]
Would doing a squash merge through the GitHub UI be enough @justaugustus? We'd still get the text of the changes, but it'd all be made into one commit.

**Comment by justaugustus** [comment]
> Would doing a squash merge through the GitHub UI be enough @justaugustus? We'd still get the text of the changes, but it'd all be made into one commit.

@hackabletype -- yep, yep. I was mobile at the time and wasn't sure if we had squashing enabled for this repo. :)

**Pull request merged**
