### PR TITLE
Review feedback updates (Front page & docs reorg)

### LINKED ISSUE #17: Reorder pages in documentation list
Please work with the maintainers to decide on the correct order for pages in these sections.

_Originally posted by @celestehorgan in https://github.com/dexidp/website/pull/8#discussion_r498477500_

### LINKED ISSUE #18: Provide a general blurb on "what is Dex?" on Documentation page
Comment: It would be good to provide a _general_ blurb on "what is Dex?" in [content/docs/_index.md].

cc @justaugustus, please tag other maintainers as you see fit.

_Originally posted by @celestehorgan in https://github.com/dexidp/website/pull/8#discussion_r498477034_

### LINKED ISSUE #19: Provide general info on connectors index page
Provide general blurb in content/docs/connectors/_index.md file.

### LINKED ISSUE #21: Home Page Content Updates
* The content you migrated into the site's index will likely need to be moved into a Getting Started page in the docs proper in future.  We tend to reserve the index pages for marketing purposes on these sites.

_Originally posted by @celestehorgan in https://github.com/dexidp/website/pull/8#issuecomment-703822774_

### LINKED ISSUE #42: CoreOS References on Home Page
Check that references to CoreOS on the home page comply with the [CNCF Website Guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) section on references to origin companies (item 2). Remove or rework references if not.

(related issue: https://github.com/dexidp/website/issues/22 item 2.)

### LINKED ISSUE #55: Update landing page
Update landing page:
- Too much going on
- Everything after first 2 paras need to go into `docs/`
  - Move to Overview page of Documentation (https://dexidp.io/docs/)
  - Break this into several pages (with page breaks on sections)
 
related to issue https://github.com/dexidp/website/issues/18

### LINKED ISSUE #57: Add Github Button to Top Level Nav
Add GitHub button to nav, next to twitter
- link to https://github.com/dexidp/dex
- to be black w/ white text/icons

This can be done fairly straightforwardly in the `config.toml` file.

### PR DESCRIPTION
**Pull request by nate-double-u**
This PR relates to feedback from a review meeting with @celestehorgan and @zacharysarah. Other reviewers welcome to share comments/concerns.

Related issues:
- Update Landing Page. (Fixes #55)
  - Home Page Content Updates. (Fixes #21)
  - CoreOS References on Homepage. (Fixes #42, updates item 2 of issue https://github.com/dexidp/website/issues/22)
  - Provide a general blurb on "what is Dex?" on Documentation page. (Fixes #18)
  - Provide general info on connectors index page. (Fixes #19)
  - Update colour scheme. (Fixes https://github.com/dexidp/website/issues/58)
- Add GitHub button to top level Nav. (Fixes #57)
- Reorder pages in documentation list. (Fixes #17)
- Move nav to left hand side. (Fixes https://github.com/dexidp/website/issues/56)

### CODE REVIEW

**Comment by nate-double-u** [comment]
Deploy preview: https://deploy-preview-59--dexidp.netlify.app/
(I'll squash all the commits before setting this PR to Ready for Review.)

**Comment by nate-double-u** [comment]
Major changes:
* https://deploy-preview-59--dexidp.netlify.app/
* https://deploy-preview-59--dexidp.netlify.app/docs/
* https://deploy-preview-59--dexidp.netlify.app/docs/connectors/

New pages:
* https://deploy-preview-59--dexidp.netlify.app/docs/id-tokens/
* https://deploy-preview-59--dexidp.netlify.app/docs/kubernetes-dex/

**Comment by nate-double-u** [comment]
Note, the proposals section won't show up during the production build as those pages are all set to draft.

Should these be removed? Is this repo the right forum for them?

Screen Shot 2020-10-22 at 10 12 45 AM

**Comment by nate-double-u** [comment]
Related issues:
- Fixes: #17
- Fixes #18
- Fixes #19
- Fixes #21
- Fixes #42
- Fixes #55
- Fixes #57

**Comment by nate-double-u** [comment]
Inviting @zacharysarah to review.

**Comment by nate-double-u** [comment]
https://github.com/dexidp/website/pull/59/commits/0261535c270f3390b1dda00e8c70cfea398904ef works with firefox, but not chrome or mobile safari. Still some work to do with it, but this at least gives the idea I was going for.

### Firefox
Screen Shot 2020-10-23 at 2 26 44 PM
Screen Shot 2020-10-23 at 2 26 38 PM

### Chrome
Screen Shot 2020-10-23 at 2 28 51 PM
Screen Shot 2020-10-23 at 2 28 46 PM

### Mobile Safari

**Comment by sagikazarmark** [comment]
Thanks @nate-double-u ! Looks good to me.

One thing though: I got used to the nav on the right side. It feels weird now. :D

**Comment by nate-double-u** [comment]
> I got used to the nav on the right side. It feels weird now. :D

Ya, I think there's a couple things making it look a bit weird -- for instance, the location of the 'edit on github' button isn't correct right now (sortof hovering above the middle of the content part rather than on it's top corner), but I haven't figured out how to move it correctly yet 😅.

Also, is the order of the Nav working for you @sagikazarmark? I've tried to re order it closer to the other lists of docs from the old README.md file, but there are some new docs that need to be listed.

Screen Shot 2020-10-24 at 12 06 42 PM

**Comment by sagikazarmark** [comment]
I think it's fine for now, although we should probably break the Overview section into smaller parts. For example: Become a maintainer and Running Integration Tests are Dex development related topics.

**Comment by zacharysarah** [comment]
@nate-double-u Thanks for incorporating feedback, this looks greatly improved. ✨ 

/lgtm
/approve

@sagikazarmark 
> I think it's fine for now, although we should probably break the Overview section into smaller parts.

Hopefully this PR sets up the Dex team for success going forward with any writers you hire.

**Review by sagikazarmark — APPROVED** [review]
Thanks!

**Pull request merged**
