### PR TITLE
Improve web asset docs

### PR DESCRIPTION
**Pull request by sagikazarmark**
Related to dexidp/dex#2054

### CODE REVIEW

**Comment by nate-double-u** [comment]
deploy preview: https://deploy-preview-94--dexidp.netlify.app/docs/templates/

**Review by nate-double-u — APPROVED** [review]

**Comment by nate-double-u** [comment]
This looks good to me @sagikazarmark, now that https://github.com/dexidp/dex/pull/2054 is merged in, should we set `draft: false` and publish?

**Comment by sagikazarmark** [comment]
Well, it's not released yet, so I'm afraid it would be confusing for people. At the same time leaving `draft: true` in the docs is something that we'll definitely forget to update when we release the next version. Any ideas?

Maybe we could introduce a variable in the config that contains the latest application version (eg. 2.28.1) and we put new docs behind feature flags, so that we only have to update the current version to release any new pages or just sections within pages. What do you think? Is it feasible with Hugo? Is it even a good idea?

**Comment by nate-double-u** [comment]
> Well, it's not released yet, so I'm afraid it would be confusing for people. At the same time leaving `draft: true` in the docs is something that we'll definitely forget to update when we release the next version. Any ideas?

I misunderstood - sorry about that. I agree, publishing now would be confusing.

> Maybe we could introduce a variable in the config that contains the latest application version (eg. 2.28.1) and we put new docs behind feature flags, so that we only have to update the current version to release any new pages or just sections within pages. What do you think? Is it feasible with Hugo? Is it even a good idea?

I think feature flags are feasible in hugo (https://jaketrent.com/post/continuous-delivery-of-static-site), though, I haven't set one up yet. Most CNCF project sites have a version structure and a dropdown selector to manage this sort of issue (they would have a 'next' or 'current' folder for up coming releases, and and a folder for each supported historical version).

Possibly we could spin off a new issue to discuss version management?

**Pull request merged**
